server:
 port: 8080
 servlet:
   context-path: /
 tomcat:
   uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  security:
    user:
      name: user
      password: 123456




jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: mjh
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

filepath:
  imagePath: /home/mjh/images